# Generated by Django 2.2.4 on 2023-12-19 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='uploaded_by',
        ),
        migrations.RemoveField(
            model_name='nursery',
            name='nursery_location',
        ),
        migrations.RemoveField(
            model_name='nursery',
            name='uploaded_by',
        ),
        migrations.RemoveField(
            model_name='nursery_section',
            name='uploaded_by',
        ),
    ]
