# Generated by Django 2.2.4 on 2023-12-19 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20231220_0051'),
    ]

    operations = [
        migrations.AddField(
            model_name='nursery',
            name='nursery_location',
            field=models.TextField(null=True),
        ),
    ]
