# Generated by Django 2.2.4 on 2023-12-20 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_nursery_nursery_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facilities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facilities_name', models.CharField(max_length=225)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Programs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_offered_name', models.CharField(max_length=225)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='nursery',
            name='facilities',
        ),
        migrations.RemoveField(
            model_name='nursery',
            name='program_offered',
        ),
        migrations.AddField(
            model_name='nursery',
            name='facilities',
            field=models.ManyToManyField(related_name='nursery', to='app.Facilities'),
        ),
        migrations.AddField(
            model_name='nursery',
            name='program_offered',
            field=models.ManyToManyField(related_name='nursery', to='app.Programs'),
        ),
    ]
