# Generated by Django 2.2.4 on 2023-12-20 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20231220_2126'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Nursery_section',
        ),
    ]
