# Generated by Django 2.2.4 on 2023-12-23 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20231223_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='nursery',
            name='image',
            field=models.TextField(null=True),
        ),
    ]
