# Generated by Django 2.2.4 on 2023-12-23 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_nursery_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='nursery',
            name='avatar',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
