# Generated by Django 2.2.4 on 2023-12-23 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_nursery_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nursery',
            name='avatar',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
