# Generated by Django 2.2.4 on 2023-12-23 17:46

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20231223_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nursery',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=app.models.random_image_filename),
        ),
    ]
